### ISSUE TITLE
中小企业校招需求调研

### ISSUE THREAD

**Issue by guoyuming** [guoyuming/OpenQuestion#1]
## 背景
求职者更多将目光集中在20%的大企业上，被它们的品牌效应和曝光吸引。只是很多资质履历一般的求职者，在简历筛选环节已经被刷。在需求的另一方，数量巨大中小企业，也更想招到，但这些精英企业在雇主市场上，没多大竞争力。

因为信息不对等，招聘和求职需求难以满足。人和公司、职位的匹配，一直是个难题。现在主流招聘网站只解决信息展示和部分通知，做的是广告的业务。需求双方难通过简历或招聘广告判断是否中意。校园招聘中，因为毕业生缺乏履历，不了解行业，信息不对称更加明显。每年将近700万毕业生，只有52%左右在4月确定offer。

企业往往做校招项目，相当于精准投放广告，同时完成部分筛选和招聘工作。大企业如格兰仕、志高、屈臣氏，预算充足，在学校做专场宣讲会。500-1000人规模企业，进入企业只做招聘，它们更愿意做联合宣讲会，而非专场宣讲会。几十人规模的小公司没有预算做校招或培训，它们买在线招聘网站账服务，找简历。

## 调研对象&场合
500人以内中小企业，20-50家：

1. 陪同拜访客户，聊天中完成
2. HR沙龙将调研问题做成设计小互动、活动、小游戏
3. 邀请HR做焦点小组
4. 加入HR交流群，伪装提问
5. 一对一正式访谈

### Q&A

1. 校招项目的负责人是谁？可以调用哪些人？相互怎么合作？流程如何？
2. 面试如何安排？比如一场地安排20人，逐一电话通知？如果安排好20人，有人临时不来，提前告知？或直接不到场，如何处理？
3. 项目中，哪部分工作量最大？筛选？组织实施面试？
4. 初筛时选简历是最重要的因素？
5. 接收简历之后，什么时候开始初筛简历，或达到什么条件开始初筛简历？如果有使用后台简历筛选系统，如何操作？
6. 简历中的“擅长技能”，可以自定义填写技能名称，比如唱歌、跑步之类的，然后选擅长精通熟悉，这部分信息对HR作用多大？
7. 做一场校招项目、或一次招聘会的成本有多少（折算成人工成本），或时间多久？
8. 使用过人力资源服务产品吗？用时候遇到什么困难？希望增加什么功能？什么功能最鸡肋？

每个问题措辞和场景还可以细化，先列出大纲。希望能集思广益，列举出尽可能多问题，50个左右，再筛选排序合并，做成调研问题大纲。

### 可能遇到的难点

1. 没有找到问题重点，也就是问不出好问题，难拿到重要信息。
2. 有些问题涉及企业核心业务或行业规则，执行者HR也不甚了解或不想透露。
3. 没有找到对的人，执行者HR没有全程操作过项目。

**Comment by guoyuming** [comment]
@浩涛
浩涛的回复：
- 处理
  - 本周内我个人做个简短回答。
  - 我可以发个课程给你，里面和招聘相关的课可能部分回答你的问题。账号认IP否则会有冲突，所以你根据兴趣和需求约个你会使用账号的时间段，我们错开使用咯。
  - 赞同要找HR社群，我现在只剩下付费社群所以没办法拉你进去，但如果有调查链接我可以帮忙转。
- 建议
  - 提纲更像是访谈，我直接转给专业负责招聘的朋友的话恐怕效果不佳。如果有个调研表之类轻量级的工具可能更便于传播。
  - 不少问题比较大和普遍，是否在专业的BBS之类了解过？或者做文献调研？
  - 你此项调研工作的需求和立场是什么？

**Comment by guoyuming** [comment]
@浩涛，谢谢你详尽的回复啊，只是简单过了一下就提出了这么多启发的信息点。针对你建议，我是这样想的：

1. 提纲是很粗略的设想，具体问题措辞会找公司HR伙伴、企业线同事验证，以及参考开智的模因－如何提一个好问题。调研表是另外一种方式，优先考虑访谈。
2. BBS确实还没有了解过，很多是行业媒体中调研和直接使用产品时候找出的问题。文献调研，这个问题棒～联想到上次沙龙我们聊到自修计划，以实际问题出发去研修。只是实际问题，比如如何做好校招业务需求调研，离源头论文差好几层，如何确定问题背后的领域？这个我们可以来一起探讨一下。
3. 需求是找到中小企业校招业务中，是否需要一个app来做流程管理，提高效率、节约成本，如果需要，有哪些需要app产品解决？立场：公司平台一个新产品／项目，或退一步，app中一个功能。

**Comment by linhaotao** [comment]
# 20170812 回复中小企业校招需求调研
## 校招项目
`- 校招项目的负责人是谁？可以调用哪些人？相互怎么合作？流程如何？`
- (方案阶段)从下至上
  - 校招由招聘模块负责人(如招聘经理)发起与执行。根据年度用人需求以及人力资源规划形成招聘需求，校招作为招聘需求一部份提出校招方案(可单独形成方案，也可包含在年度招聘方案里)，并提出经费预算(一般提前一年做下一年度预算)    
  - HR部门负责人(如人力资源主管)审核校招方案并参与方案审议。
  - HR业务领导(如人力资源副总裁)以及财务业务领导审批校招方案。
- (执行阶段)调用及合作
  - 招聘线人员:如招聘经理调动招聘专员，若无分工这么细，则成立临时项目组，由部门负责人协调部门人员。
  - 招聘需求提出单位:如提出招聘需求的业务部门，一般是直接参与校招实施，如在宣讲会或者校招现场进行简历筛选及初面。这种直接在校招现场初面的好处是效率，能更快更好确定学生。
    - 例子:校招日，由HR部门组织校招现场，并调动用人需求部门人员参与，现场收简历后进行简短面谈(一般是一到两个结构化问题)，现场对面谈合适者发放面试通知条，安排应聘者(马上，或当天其他时间)到会议室进行正式一面(一般提前向学校预约课室)
  - 招聘外包服务商。预算充裕的单位会将校招方案的所有实施(联系学校、在地宣传、场地落实等)全包给服务商。
- 流程:见上，从「方案阶段」——「执行阶段」顺着下来即为一般流程。
`- 项目中，哪部分工作量最大？筛选？组织实施面试？`
“功夫在书外”组织环节最繁杂，因为涉及资源调动与协调，其他如简历筛选或者面试都可按设定好程序进行。
`- 做一场校招项目、或一次招聘会的成本有多少（折算成人工成本），或时间多久？`
- 费用:丰俭由人，全部自己策划实施的话，成本主要是A场租(1个教室半天有的收1K，有的免费)、B物料(宣传材料0.5K)、C人工(根据工作人员月薪折算)、D人员差旅费用(涉及省外项目的交通费、住宿以及差旅补助，根据具体单位定)、E宣传(一般在校内网发布是免费的，若同期在招聘网站上发布信息就涉及宣传费用，宣传物料费见上)；若外包，则有服务溢价，即上部份的A\B\E交由外包公司全搞定，但需要额外支付外包公司工作人员劳务费及项目服务费，而C\D费用可能仍存在。
- 时间
  - 预算周期:跨年度
  - 具体实施:半个月至一个月 
`- 使用过人力资源服务产品吗？用时候遇到什么困难？希望增加什么功能？什么功能最鸡肋？`
- 使用过:一般招聘服务(广告、简历搜索下载、招聘系统)；测评服务；校招外包服务。
- 困难
  - 成本:成本较高，做招聘效果评估时时间线较长。
  - 产品都是标准化的，要满足个性化又是一笔额外不菲的成本。
- 希望增加功能:暂无。
- 鸡肋功能:暂无。
## 简历筛选与面试考核
`- 接收简历之后，什么时候开始初筛简历，或达到什么条件开始初筛简历？如果有使用后台简历筛选系统，如何操作？`
见第一部分回答，一般是大公司使用的网申系统，网申系统是对申请人标准化的筛选。
`- 初筛时选简历是最重要的因素？`
- 简历要精要，直接:看着不爽的直接扔
- 满足岗位基本需求清单
`- 简历中的“擅长技能”，可以自定义填写技能名称，比如唱歌、跑步之类的，然后选擅长精通熟悉，这部分信息对HR作用多大？`
校招场景下无多大用处。
`- 面试如何安排？比如一场地安排20人，逐一电话通知？如果安排好20人，有人临时不来，提前告知？或直接不到场，如何处理？`
校招场景下，一类操作见第一部分；另外普通点的就是邮件或者短信通知，无论有无告知，不到场即默认弃权(太常见了经常被放鸽子)
